### ISSUE TITLE
Replace PlanetJogger engine

### ISSUE THREAD

**Issue by ghost** [rozie/PlanetJogger#19]
See http://planetgolang.com/about.html

**Comment by rozie** [comment]
Well, it looks like not developed anymore too. Of course newer than Planet Venus, but still...

Right now I don't see an urgent reason to look for replacement, but if I decide to change, I'd rather prefer some software written in language I use (Perl/Python).

https://people.gnome.org/~jdub/bzr/planet/2.0/ is also old, but seems running and may be worth taking a look.
