### ISSUE TITLE
[IMPORTANT] Add Jogger favicon and graphics (header, footer) when they are published with license

### ISSUE THREAD

**Issue by d33tah** [rozie/PlanetJogger#2]

**Comment by rozie** [comment]
Waiting for permission/license for favicon and graphics from jogger.pl owners.

**Comment by kutzowsky** [comment]
I've coded a very basic template with look and feel from Jogger.pl using Bootstrap framework. We might use it after permission/license and some additional work.

**Comment by d4rky-pl** [comment]
Hey, [this is what Piotrek replied when I asked if it's OK to open source Jogger.pl template](https://twitter.com/riddle/status/701733681912799232).

Considering I didn't find necessary time to clean up and release Jogger.pl source - and Robert explicitly asked me not to until we disable current Jogger.pl with it's panel completely as there are probably multiple security vulnerabilities at this point that we don't have time to fix - I believe it's perfectly fine for you to continue Jogger legacy and use designs, graphics etc. I was given permission to open source and use it and I give you my blessing to do so.

You can always ask Piotrek directly on Twitter if you want to be extra-sure (just send him a link here so he knows I'm OK as well) as I'm not a lawyer etc. but I don't see how this would ever become a problem (I'm just a bit paranoid after following Oracle v Google case lately ;)).

**Comment by d4rky-pl** [comment]
If you have any more questions or need help just ping me directly via e-mail or Twitter. I don't follow comments on Jogger.pl anymore and you could've started poking around almost two months ago if you didn't wait for my reply :)

**Comment by rozie** [comment]
WIP then.
And there's no hurry. ;-)

**Comment by rozie** [comment]
I guess it's done more or less, no need to keep issue open.
